# Generated by Django 5.1.1 on 2024-10-28 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='bike_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('company', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('drop_date', models.DateField()),
                ('drop_time', models.DateField()),
                ('bike_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renter.bike')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renter.brand'),
        ),
    ]
