# Generated by Django 5.1.1 on 2024-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='drop_time',
            field=models.TimeField(),
        ),
    ]
