# Generated by Django 5.1.1 on 2024-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_alter_booking_drop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
