# Generated by Django 5.1.1 on 2024-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0003_remove_booking_id_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
