# Generated by Django 5.1.1 on 2024-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0004_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
