# Generated by Django 5.1.1 on 2024-11-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0005_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
