# Generated by Django 5.0.4 on 2025-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True),
        ),
    ]
