# Generated by Django 5.0.4 on 2025-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0007_booking_cancellation_reason_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per day in rupees', max_digits=10),
        ),
    ]
