# Generated by Django 5.0.4 on 2025-10-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0008_bike_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the booking', max_digits=10),
        ),
    ]
