# Generated by Django 5.0.4 on 2025-10-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0010_bike_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='bike',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per hour in rupees', max_digits=10),
        ),
    ]
